-- ===========================================================================
-- SGDF — V101 · Calendário de feriados
-- GERADO por tools/gerar_feriados.py — NÃO EDITAR À MÃO.
--
-- História F0-06 (cap. 7.3). Anos 2025–2032.
-- Móveis derivados da Páscoa; fixos da legislação federal e estadual.
-- Linhas com [FACULTATIVO] na descrição são ponto facultativo federal, não
-- feriado: mantê-las ou não é decisão de cadastro. Ver ERRATA E-07.
--
-- Feriados MUNICIPAIS não estão aqui: dependem do município de cada
-- contrato e não constam de nenhuma fonte do pacote. Cadastrar antes de
-- usar prazo em dia útil para contratos cujo município tenha feriado local.
-- ===========================================================================

BEGIN;

INSERT INTO calendario_feriados (uf, municipio, data, descricao, criado_por)
VALUES
    (NULL, NULL, '2025-01-01', 'Confraternização Universal', 'carga-inicial-feriados'),
    (NULL, NULL, '2025-03-03', '[FACULTATIVO] Carnaval (segunda-feira)', 'carga-inicial-feriados'),
    (NULL, NULL, '2025-03-04', '[FACULTATIVO] Carnaval (terça-feira)', 'carga-inicial-feriados'),
    ('CE', NULL, '2025-03-25', 'Data Magna do Ceará', 'carga-inicial-feriados'),
    (NULL, NULL, '2025-04-18', 'Sexta-Feira Santa', 'carga-inicial-feriados'),
    (NULL, NULL, '2025-04-21', 'Tiradentes', 'carga-inicial-feriados'),
    (NULL, NULL, '2025-05-01', 'Dia do Trabalho', 'carga-inicial-feriados'),
    (NULL, NULL, '2025-06-19', '[FACULTATIVO] Corpus Christi', 'carga-inicial-feriados'),
    (NULL, NULL, '2025-09-07', 'Independência do Brasil', 'carga-inicial-feriados'),
    ('RS', NULL, '2025-09-20', 'Revolução Farroupilha', 'carga-inicial-feriados'),
    (NULL, NULL, '2025-10-12', 'Nossa Senhora Aparecida', 'carga-inicial-feriados'),
    (NULL, NULL, '2025-11-02', 'Finados', 'carga-inicial-feriados'),
    (NULL, NULL, '2025-11-15', 'Proclamação da República', 'carga-inicial-feriados'),
    (NULL, NULL, '2025-11-20', 'Dia Nacional de Zumbi e da Consciência Negra', 'carga-inicial-feriados'),
    (NULL, NULL, '2025-12-25', 'Natal', 'carga-inicial-feriados'),
    (NULL, NULL, '2026-01-01', 'Confraternização Universal', 'carga-inicial-feriados'),
    (NULL, NULL, '2026-02-16', '[FACULTATIVO] Carnaval (segunda-feira)', 'carga-inicial-feriados'),
    (NULL, NULL, '2026-02-17', '[FACULTATIVO] Carnaval (terça-feira)', 'carga-inicial-feriados'),
    ('CE', NULL, '2026-03-25', 'Data Magna do Ceará', 'carga-inicial-feriados'),
    (NULL, NULL, '2026-04-03', 'Sexta-Feira Santa', 'carga-inicial-feriados'),
    (NULL, NULL, '2026-04-21', 'Tiradentes', 'carga-inicial-feriados'),
    (NULL, NULL, '2026-05-01', 'Dia do Trabalho', 'carga-inicial-feriados'),
    (NULL, NULL, '2026-06-04', '[FACULTATIVO] Corpus Christi', 'carga-inicial-feriados'),
    (NULL, NULL, '2026-09-07', 'Independência do Brasil', 'carga-inicial-feriados'),
    ('RS', NULL, '2026-09-20', 'Revolução Farroupilha', 'carga-inicial-feriados'),
    (NULL, NULL, '2026-10-12', 'Nossa Senhora Aparecida', 'carga-inicial-feriados'),
    (NULL, NULL, '2026-11-02', 'Finados', 'carga-inicial-feriados'),
    (NULL, NULL, '2026-11-15', 'Proclamação da República', 'carga-inicial-feriados'),
    (NULL, NULL, '2026-11-20', 'Dia Nacional de Zumbi e da Consciência Negra', 'carga-inicial-feriados'),
    (NULL, NULL, '2026-12-25', 'Natal', 'carga-inicial-feriados'),
    (NULL, NULL, '2027-01-01', 'Confraternização Universal', 'carga-inicial-feriados'),
    (NULL, NULL, '2027-02-08', '[FACULTATIVO] Carnaval (segunda-feira)', 'carga-inicial-feriados'),
    (NULL, NULL, '2027-02-09', '[FACULTATIVO] Carnaval (terça-feira)', 'carga-inicial-feriados'),
    ('CE', NULL, '2027-03-25', 'Data Magna do Ceará', 'carga-inicial-feriados'),
    (NULL, NULL, '2027-03-26', 'Sexta-Feira Santa', 'carga-inicial-feriados'),
    (NULL, NULL, '2027-04-21', 'Tiradentes', 'carga-inicial-feriados'),
    (NULL, NULL, '2027-05-01', 'Dia do Trabalho', 'carga-inicial-feriados'),
    (NULL, NULL, '2027-05-27', '[FACULTATIVO] Corpus Christi', 'carga-inicial-feriados'),
    (NULL, NULL, '2027-09-07', 'Independência do Brasil', 'carga-inicial-feriados'),
    ('RS', NULL, '2027-09-20', 'Revolução Farroupilha', 'carga-inicial-feriados'),
    (NULL, NULL, '2027-10-12', 'Nossa Senhora Aparecida', 'carga-inicial-feriados'),
    (NULL, NULL, '2027-11-02', 'Finados', 'carga-inicial-feriados'),
    (NULL, NULL, '2027-11-15', 'Proclamação da República', 'carga-inicial-feriados'),
    (NULL, NULL, '2027-11-20', 'Dia Nacional de Zumbi e da Consciência Negra', 'carga-inicial-feriados'),
    (NULL, NULL, '2027-12-25', 'Natal', 'carga-inicial-feriados'),
    (NULL, NULL, '2028-01-01', 'Confraternização Universal', 'carga-inicial-feriados'),
    (NULL, NULL, '2028-02-28', '[FACULTATIVO] Carnaval (segunda-feira)', 'carga-inicial-feriados'),
    (NULL, NULL, '2028-02-29', '[FACULTATIVO] Carnaval (terça-feira)', 'carga-inicial-feriados'),
    ('CE', NULL, '2028-03-25', 'Data Magna do Ceará', 'carga-inicial-feriados'),
    (NULL, NULL, '2028-04-14', 'Sexta-Feira Santa', 'carga-inicial-feriados'),
    (NULL, NULL, '2028-04-21', 'Tiradentes', 'carga-inicial-feriados'),
    (NULL, NULL, '2028-05-01', 'Dia do Trabalho', 'carga-inicial-feriados'),
    (NULL, NULL, '2028-06-15', '[FACULTATIVO] Corpus Christi', 'carga-inicial-feriados'),
    (NULL, NULL, '2028-09-07', 'Independência do Brasil', 'carga-inicial-feriados'),
    ('RS', NULL, '2028-09-20', 'Revolução Farroupilha', 'carga-inicial-feriados'),
    (NULL, NULL, '2028-10-12', 'Nossa Senhora Aparecida', 'carga-inicial-feriados'),
    (NULL, NULL, '2028-11-02', 'Finados', 'carga-inicial-feriados'),
    (NULL, NULL, '2028-11-15', 'Proclamação da República', 'carga-inicial-feriados'),
    (NULL, NULL, '2028-11-20', 'Dia Nacional de Zumbi e da Consciência Negra', 'carga-inicial-feriados'),
    (NULL, NULL, '2028-12-25', 'Natal', 'carga-inicial-feriados'),
    (NULL, NULL, '2029-01-01', 'Confraternização Universal', 'carga-inicial-feriados'),
    (NULL, NULL, '2029-02-12', '[FACULTATIVO] Carnaval (segunda-feira)', 'carga-inicial-feriados'),
    (NULL, NULL, '2029-02-13', '[FACULTATIVO] Carnaval (terça-feira)', 'carga-inicial-feriados'),
    ('CE', NULL, '2029-03-25', 'Data Magna do Ceará', 'carga-inicial-feriados'),
    (NULL, NULL, '2029-03-30', 'Sexta-Feira Santa', 'carga-inicial-feriados'),
    (NULL, NULL, '2029-04-21', 'Tiradentes', 'carga-inicial-feriados'),
    (NULL, NULL, '2029-05-01', 'Dia do Trabalho', 'carga-inicial-feriados'),
    (NULL, NULL, '2029-05-31', '[FACULTATIVO] Corpus Christi', 'carga-inicial-feriados'),
    (NULL, NULL, '2029-09-07', 'Independência do Brasil', 'carga-inicial-feriados'),
    ('RS', NULL, '2029-09-20', 'Revolução Farroupilha', 'carga-inicial-feriados'),
    (NULL, NULL, '2029-10-12', 'Nossa Senhora Aparecida', 'carga-inicial-feriados'),
    (NULL, NULL, '2029-11-02', 'Finados', 'carga-inicial-feriados'),
    (NULL, NULL, '2029-11-15', 'Proclamação da República', 'carga-inicial-feriados'),
    (NULL, NULL, '2029-11-20', 'Dia Nacional de Zumbi e da Consciência Negra', 'carga-inicial-feriados'),
    (NULL, NULL, '2029-12-25', 'Natal', 'carga-inicial-feriados'),
    (NULL, NULL, '2030-01-01', 'Confraternização Universal', 'carga-inicial-feriados'),
    (NULL, NULL, '2030-03-04', '[FACULTATIVO] Carnaval (segunda-feira)', 'carga-inicial-feriados'),
    (NULL, NULL, '2030-03-05', '[FACULTATIVO] Carnaval (terça-feira)', 'carga-inicial-feriados'),
    ('CE', NULL, '2030-03-25', 'Data Magna do Ceará', 'carga-inicial-feriados'),
    (NULL, NULL, '2030-04-19', 'Sexta-Feira Santa', 'carga-inicial-feriados'),
    (NULL, NULL, '2030-04-21', 'Tiradentes', 'carga-inicial-feriados'),
    (NULL, NULL, '2030-05-01', 'Dia do Trabalho', 'carga-inicial-feriados'),
    (NULL, NULL, '2030-06-20', '[FACULTATIVO] Corpus Christi', 'carga-inicial-feriados'),
    (NULL, NULL, '2030-09-07', 'Independência do Brasil', 'carga-inicial-feriados'),
    ('RS', NULL, '2030-09-20', 'Revolução Farroupilha', 'carga-inicial-feriados'),
    (NULL, NULL, '2030-10-12', 'Nossa Senhora Aparecida', 'carga-inicial-feriados'),
    (NULL, NULL, '2030-11-02', 'Finados', 'carga-inicial-feriados'),
    (NULL, NULL, '2030-11-15', 'Proclamação da República', 'carga-inicial-feriados'),
    (NULL, NULL, '2030-11-20', 'Dia Nacional de Zumbi e da Consciência Negra', 'carga-inicial-feriados'),
    (NULL, NULL, '2030-12-25', 'Natal', 'carga-inicial-feriados'),
    (NULL, NULL, '2031-01-01', 'Confraternização Universal', 'carga-inicial-feriados'),
    (NULL, NULL, '2031-02-24', '[FACULTATIVO] Carnaval (segunda-feira)', 'carga-inicial-feriados'),
    (NULL, NULL, '2031-02-25', '[FACULTATIVO] Carnaval (terça-feira)', 'carga-inicial-feriados'),
    ('CE', NULL, '2031-03-25', 'Data Magna do Ceará', 'carga-inicial-feriados'),
    (NULL, NULL, '2031-04-11', 'Sexta-Feira Santa', 'carga-inicial-feriados'),
    (NULL, NULL, '2031-04-21', 'Tiradentes', 'carga-inicial-feriados'),
    (NULL, NULL, '2031-05-01', 'Dia do Trabalho', 'carga-inicial-feriados'),
    (NULL, NULL, '2031-06-12', '[FACULTATIVO] Corpus Christi', 'carga-inicial-feriados'),
    (NULL, NULL, '2031-09-07', 'Independência do Brasil', 'carga-inicial-feriados'),
    ('RS', NULL, '2031-09-20', 'Revolução Farroupilha', 'carga-inicial-feriados'),
    (NULL, NULL, '2031-10-12', 'Nossa Senhora Aparecida', 'carga-inicial-feriados'),
    (NULL, NULL, '2031-11-02', 'Finados', 'carga-inicial-feriados'),
    (NULL, NULL, '2031-11-15', 'Proclamação da República', 'carga-inicial-feriados'),
    (NULL, NULL, '2031-11-20', 'Dia Nacional de Zumbi e da Consciência Negra', 'carga-inicial-feriados'),
    (NULL, NULL, '2031-12-25', 'Natal', 'carga-inicial-feriados'),
    (NULL, NULL, '2032-01-01', 'Confraternização Universal', 'carga-inicial-feriados'),
    (NULL, NULL, '2032-02-09', '[FACULTATIVO] Carnaval (segunda-feira)', 'carga-inicial-feriados'),
    (NULL, NULL, '2032-02-10', '[FACULTATIVO] Carnaval (terça-feira)', 'carga-inicial-feriados'),
    ('CE', NULL, '2032-03-25', 'Data Magna do Ceará', 'carga-inicial-feriados'),
    (NULL, NULL, '2032-03-26', 'Sexta-Feira Santa', 'carga-inicial-feriados'),
    (NULL, NULL, '2032-04-21', 'Tiradentes', 'carga-inicial-feriados'),
    (NULL, NULL, '2032-05-01', 'Dia do Trabalho', 'carga-inicial-feriados'),
    (NULL, NULL, '2032-05-27', '[FACULTATIVO] Corpus Christi', 'carga-inicial-feriados'),
    (NULL, NULL, '2032-09-07', 'Independência do Brasil', 'carga-inicial-feriados'),
    ('RS', NULL, '2032-09-20', 'Revolução Farroupilha', 'carga-inicial-feriados'),
    (NULL, NULL, '2032-10-12', 'Nossa Senhora Aparecida', 'carga-inicial-feriados'),
    (NULL, NULL, '2032-11-02', 'Finados', 'carga-inicial-feriados'),
    (NULL, NULL, '2032-11-15', 'Proclamação da República', 'carga-inicial-feriados'),
    (NULL, NULL, '2032-11-20', 'Dia Nacional de Zumbi e da Consciência Negra', 'carga-inicial-feriados'),
    (NULL, NULL, '2032-12-25', 'Natal', 'carga-inicial-feriados')
ON CONFLICT DO NOTHING;

INSERT INTO log_auditoria (ator, papel, acao, objeto_tipo, resultado, detalhe)
VALUES ('carga-inicial-feriados', 'MIGRACAO', 'CARGA_FERIADOS', 'calendario_feriados', 'SUCESSO',
        '{"linhas": 120, "ano_inicial": 2025, "ano_final": 2032}'::jsonb);

COMMIT;
